### ISSUE TITLE
Werewolf in level 6

### ISSUE THREAD

**Issue by Aspirin18** [Harchvertelol/Dangerous-Dave-2-Modification-Edition#3]
The first werewolf at level 6 runs off the screen after jumping down from the platform. And does not come back.

**Comment by Harchvertelol** [comment]
Fixed as much as possible. The fix will be in the next version (after v0.6).

If this is fixed by current remakes so that it was like in the original, then the ghost at the beginning of the 6th level will arrive immediately (which, it seems to me, spoils the gameplay much more). To fully comply with the original, the ideology of processing monsters must be changed. I'll think about it.

**Comment by Harchvertelol** [comment]
Fixed in the next version (after 0.6).
